#ifndef TINY_SKIA_H
#define TINY_SKIA_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */



struct ts_path;

struct ts_path_builder;

struct ts_pixmap;

struct ts_transform {
  float sx;
  float kx;
  float ky;
  float sy;
  float tx;
  float ty;
};

struct ts_color {
  uint8_t r;
  uint8_t g;
  uint8_t b;
  uint8_t a;
};

struct ts_rect {
  float x0;
  float y0;
  float x1;
  float y1;
};

extern "C" {

void ts_close(ts_path_builder *p);

void ts_line_to(ts_path_builder *p, float x, float y);

void ts_move_to(ts_path_builder *p, float x, float y);

ts_path_builder *ts_path_builder_create();

ts_path *ts_path_builder_finish(ts_path_builder *b);

void ts_path_destroy(ts_path *b);

size_t ts_path_len(ts_path *b);

ts_pixmap *ts_pixmap_create(uint32_t width, uint32_t height);

void ts_pixmap_destroy(ts_pixmap *pixmap);

void ts_pixmap_fill_path(ts_pixmap *pixmap,
                         const ts_path *path,
                         ts_transform transform,
                         ts_color color);

void ts_pixmap_fill_rect(ts_pixmap *pixmap, ts_rect rect, ts_transform transform, ts_color color);

void ts_pixmap_save(ts_pixmap *pixmap, const char *path);

ts_transform ts_transform_combine(ts_transform a, ts_transform b);

ts_transform ts_transform_identity();

ts_transform ts_transform_scale(float sx, float sy);

}  // extern "C"

#endif  // TINY_SKIA_H
