#ifndef TINY_SKIA_H
#define TINY_SKIA_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */



struct ts_transform {
  float sx;
  float kx;
  float ky;
  float sy;
  float tx;
  float ty;
};

extern "C" {

ts_transform ts_transform_combine(ts_transform a, ts_transform b);

ts_transform ts_transform_identity();

ts_transform ts_transform_scale(float sx, float sy);

}  // extern "C"

#endif  // TINY_SKIA_H
